# Generated by Django 3.0 on 2020-12-24 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('qualification', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
            ],
        ),
    ]
