# Generated by Django 3.0 on 2020-12-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meets2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers_list',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='teachers_list',
            name='teacher_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
