# Generated by Django 3.0 on 2020-12-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meets2', '0003_auto_20201228_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers_list',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
